name: Use Case - PROD

on:
  workflow_dispatch:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  PROD:
    environment: PROD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Run use case tests
      run:  |
              cd test/k6
              docker compose run k6 run /src/tests/end2end.js -e subskey=${{ secrets.APIM_SUBSKEY }} -e env=${{ vars.ENV }} -e org=${{ vars.ORG }} -e app=${{ vars.APP }} -e userId=${{ secrets.USER_ID }} -e personNumber=${{ secrets.PERSON_NUMBER }} -e partyId=${{ secrets.PARTY_ID }} -e username=${{ secrets.USERNAME }} -e password=${{ secrets.PASSWORD }}

  report-status:
    name: Report status
    runs-on: ubuntu-latest
    needs: [PROD]
    if: always() && contains(join(needs.*.result, ','), 'failure')
    steps:
      - name: Build failure report
        run: |
          report=" :warning: FileScan use case test failure in production :warning: \n"
          report+="Workflow available here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "stepreport="$report >> $GITHUB_ENV
      - name: Report failure to Slack
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_PROD }}
          payload: |
              {
                "text": "${{ env.stepreport }}"
              }

