name: Use Case - PROD

on:
  schedule:
  - cron: '*/10 * * * *'
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  PROD:
    environment: PROD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run use case tests
      run:  |
              cd test/k6
              docker-compose run k6 run /src/tests/end2end.js -e subskey=${{ secrets.APIM_SUBSKEY }} -e env=${{ vars.ENV }} -e org=${{ vars.ORG }} -e app=${{ vars.APP }} -e userId=${{ secrets.USER_ID }} -e personNumber=${{ secrets.PERSON_NUMBER }} -e partyId=${{ secrets.PARTY_ID }} -e username=${{ secrets.USERNAME }} -e password=${{ secrets.PASSWORD }}

  report-status:
    name: Report status
    runs-on: ubuntu-latest
    needs: [PROD]
    if: always() && contains(join(needs.*.result, ','), 'failure')
    steps:
      - name: Build failure report
        run: |
          echo "stepreport=:warning: Use case test failure in PRODUCTION! :warning:" >> $GITHUB_ENV

      - name: Report failure to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
              {
                "text": "${{ env.stepreport }}"
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PROD_CRITICAL }}